// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// The `DefaultFirebaseOptions` class provides a static method to get the current Firebase options
/// based on the platform, and it includes a constant variable `web` with the Firebase options for web
/// platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The code block is defining a constant variable named `web` of type `FirebaseOptions`. It is
  /// assigning a new instance of `FirebaseOptions` with the specified values to the `web` variable.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETiumHKz7tuDLekNS-ymiMbhqC-6JKAU',
    appId: '1:903718502255:web:231dfa27fef11c86ceb29a',
    messagingSenderId: '903718502255',
    projectId: 'stockmanager-41687',
    authDomain: 'stockmanager-41687.firebaseapp.com',
    storageBucket: 'stockmanager-41687.appspot.com',
  );
}
